# python chunk, generation of adata file is not complete when using in R chunk
# Load loom file generated with velocyto
adata_py = scv.read_loom(filename='/mnt/Data1/public_vignettes/cellranger_output/neuron_1k/velocyto/neuron_1k.loom')
adata_py.var_names_make_unique()
# python chunk, generation of adata file is not complete when using in R chunk
# Load loom file generated with velocyto
adata_py = r.scv.read_loom(filename='/mnt/Data1/public_vignettes/cellranger_output/neuron_1k/velocyto/neuron_1k.loom')
adata_py.var_names_make_unique()
# python chunk, because of errors when trying to subset it in r chunk
cells = list(r.umap_coordinates_py.index)
r.adata = r.adata[cells]
r.adata.obsm['X_umap'] = r.umap_coordinates_py[r.adata.obs_names.to_list()].values
r.adata.obs['clusters'] = r.meta_data_py['clusters'].loc[r.adata.obs_names.to_list()].values)
r.adata._X
import scvelo as scv
import pandas as pd
import anndata
scv.logging.print_version()
# python chunk, generation of adata file is not complete when using in R chunk
# Load loom file generated with velocyto
adata = r.scv.read_loom(filename='/mnt/Data1/public_vignettes/cellranger_output/neuron_1k/velocyto/neuron_1k.loom')
adata.var_names_make_unique()
reticulate::repl_python()
